server:
  port: 8083
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookapp

  application:
    name: favouriteservice
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8007/eureka
      