server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookapp
      
  application:
    name: recommendation-service
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8007/eureka
